package dev.mkiros.perch.data.parse

import com.google.common.truth.Truth.assertThat
import java.nio.charset.Charset
import kotlin.random.Random
import org.junit.Test

/**
 * Format dispatch, per SPEC.md §5: the root element decides which parser runs — never the
 * URL, never the `Content-Type`. Anything that is not a feed comes back as
 * [ParseResult.Failure], and nothing in here is ever allowed to throw.
 */
class FeedParserTest {

    private val parser = FeedParser()

    private fun parse(
        xml: String,
        contentType: String? = null,
        requestUrl: String? = "https://example.com/feed.xml",
        charset: Charset = Charsets.UTF_8,
    ) = parser.parse(xml.toByteArray(charset), contentType, requestUrl)

    private fun success(xml: String, contentType: String? = null) =
        parse(xml, contentType) as? ParseResult.Success
            ?: error("expected Success, got ${parse(xml, contentType)}")

    // ---- 1. one document per format ----------------------------------------------

    private val rss = """
        <?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0">
          <channel>
            <title>An RSS feed</title>
            <link>https://birdwire.example/</link>
            <item><title>Post</title><link>https://birdwire.example/post</link></item>
          </channel>
        </rss>
    """.trimIndent()

    private val atom = """
        <?xml version="1.0" encoding="UTF-8"?>
        <feed xmlns="http://www.w3.org/2005/Atom">
          <title>An Atom feed</title>
          <link rel="alternate" href="https://birdwire.example/" />
          <entry>
            <title>Post</title>
            <id>tag:birdwire,2025:1</id>
            <link href="https://birdwire.example/post" />
          </entry>
        </feed>
    """.trimIndent()

    private val rdf = """
        <?xml version="1.0" encoding="UTF-8"?>
        <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
                 xmlns="http://purl.org/rss/1.0/">
          <channel><title>An RDF feed</title><link>https://birdwire.example/</link></channel>
          <item rdf:about="https://birdwire.example/post"><title>Post</title></item>
        </rdf:RDF>
    """.trimIndent()

    @Test
    fun `dispatches an rss document to the rss parser`() {
        assertThat(success(rss).feed.title).isEqualTo("An RSS feed")
    }

    @Test
    fun `dispatches an atom document to the atom parser`() {
        assertThat(success(atom).feed.title).isEqualTo("An Atom feed")
    }

    @Test
    fun `dispatches an rdf document to the rdf parser`() {
        assertThat(success(rdf).feed.title).isEqualTo("An RDF feed")
    }

    @Test
    fun `every format yields the entry it describes`() {
        listOf(rss, atom, rdf).forEach { document ->
            assertThat(success(document).feed.entries.single().title).isEqualTo("Post")
        }
    }

    // ---- 2. dispatch ignores everything except the root element -------------------

    @Test
    fun `ignores a content type that contradicts the document`() {
        val result = success(atom, contentType = "application/rss+xml; charset=utf-8")

        assertThat(result.feed.title).isEqualTo("An Atom feed")
    }

    @Test
    fun `parses a feed served as plain text`() {
        assertThat(success(rss, contentType = "text/plain").feed.title).isEqualTo("An RSS feed")
    }

    @Test
    fun `parses a feed whose root sits behind a comment and a stylesheet instruction`() {
        val result = success(
            """
            <?xml version="1.0" encoding="UTF-8"?>
            <?xml-stylesheet type="text/xsl" href="/feed.xsl"?>
            <!-- generated by something -->
            <rss version="2.0"><channel><title>Behind a preamble</title></channel></rss>
            """.trimIndent(),
        )

        assertThat(result.feed.title).isEqualTo("Behind a preamble")
    }

    // ---- 3. everything that is not a feed -----------------------------------------

    @Test
    fun `fails on an html page`() {
        val result = parse(
            """
            <!DOCTYPE html>
            <html><head><title>A blog</title></head><body><p>Hello</p></body></html>
            """.trimIndent(),
        )

        assertThat(result).isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `fails on xml that is well formed but not a feed`() {
        val result = parse("""<?xml version="1.0"?><opml version="2.0"><body /></opml>""")

        assertThat(result).isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `fails on garbage`() {
        assertThat(parse("not xml, not html, just words"))
            .isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `fails on an empty document`() {
        assertThat(parser.parse(ByteArray(0), null, "https://example.com/feed.xml"))
            .isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `fails on whitespace only`() {
        assertThat(parse("   \n\t  ")).isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `fails on an rss root with no channel`() {
        assertThat(parse("""<rss version="2.0"></rss>"""))
            .isInstanceOf(ParseResult.Failure::class.java)
    }

    @Test
    fun `every failure carries a reason a human can read`() {
        val failures = listOf(
            parse("<html><body>hi</body></html>"),
            parse("garbage"),
            parser.parse(ByteArray(0), null, null),
        ).map { it as ParseResult.Failure }

        failures.forEach { assertThat(it.reason).isNotEmpty() }
    }

    // ---- 4. encoding ---------------------------------------------------------------

    @Test
    fun `honours the charset in the xml declaration over the http content type`() {
        val document = """
            <?xml version="1.0" encoding="ISO-8859-1"?>
            <rss version="2.0"><channel><title>Caf&#233; brûlé</title></channel></rss>
        """.trimIndent()

        val result = parser.parse(
            document.toByteArray(Charsets.ISO_8859_1),
            "application/rss+xml; charset=utf-8",
            null,
        ) as ParseResult.Success

        assertThat(result.feed.title).isEqualTo("Café brûlé")
    }

    @Test
    fun `falls back to the http charset when the declaration omits one`() {
        val document = """<rss version="2.0"><channel><title>brûlé</title></channel></rss>"""

        val result = parser.parse(
            document.toByteArray(Charsets.ISO_8859_1),
            "application/rss+xml; charset=iso-8859-1",
            null,
        ) as ParseResult.Success

        assertThat(result.feed.title).isEqualTo("brûlé")
    }

    @Test
    fun `does not crash on bytes that contradict their declared charset`() {
        val declared = """<?xml version="1.0" encoding="UTF-8"?>
            <rss version="2.0"><channel><title>ok</title></channel></rss>
        """.trimIndent().toByteArray(Charsets.UTF_8)
        val corrupted = declared + byteArrayOf(0xC3.toByte(), 0x28, 0xA9.toByte())

        val result = parser.parse(corrupted, null, null)

        assertThat(result).isInstanceOf(ParseResult.Success::class.java)
    }

    @Test
    fun `ignores an unknown charset name rather than failing`() {
        val result = parse(rss, contentType = "application/rss+xml; charset=x-not-a-charset")

        assertThat(result).isInstanceOf(ParseResult.Success::class.java)
    }

    // ---- 5. the pathological input ------------------------------------------------

    @Test
    fun `rejects five megabytes of random bytes quickly and without exhausting memory`() {
        val noise = Random(20260807).nextBytes(5 * 1024 * 1024)

        val startedAt = System.nanoTime()
        val result = parser.parse(noise, null, "https://example.com/feed.xml")
        val elapsedMillis = (System.nanoTime() - startedAt) / 1_000_000

        assertThat(result).isInstanceOf(ParseResult.Failure::class.java)
        assertThat(elapsedMillis).isLessThan(2_000L)
    }

    @Test
    fun `rejects five megabytes of html without parsing it`() {
        val page = buildString {
            append("<!DOCTYPE html><html><body>")
            while (length < 5 * 1024 * 1024) append("<div class='post'>a paragraph of text</div>")
            append("</body></html>")
        }

        val startedAt = System.nanoTime()
        val result = parse(page)
        val elapsedMillis = (System.nanoTime() - startedAt) / 1_000_000

        assertThat(result).isInstanceOf(ParseResult.Failure::class.java)
        assertThat(elapsedMillis).isLessThan(2_000L)
    }
}
